### ISSUE TITLE
Doesnt show the added files to list

### ISSUE THREAD

**Issue by ngmgit** [TeamSTEP/unity-push-checker#2]
Description: Added files should show up in the list but the list is empty, although the scanned file no is updated properly.

![image](https://user-images.githubusercontent.com/10939602/94991469-ffd53080-05a0-11eb-9d20-b92f1a8bd351.png)

**Comment by hoonsubin** [comment]
thanks for the issue, that was bugging me as well.
I've added a conditional check to make the bot only comment when there are changes made to an important file type: https://github.com/TeamSTEP/unity-push-checker/pull/3
I hope this solves it
